Repository team-badminton/imgar-frontend, pull requests merged in 2021-09, with the labels that each got.

#50 RTK query를 사용해 API 요청 기능 구현
  src/custom.d.ts
  src/redux/api/normalizers.ts
  src/redux/api/types/fetchData.ts
  src/redux/api/types/queries.ts
  src/redux/api/v3.ts
  src/redux/index.ts
  src/redux/storeTypes.ts
Labels: ✨Feature

#59 Search 컴포넌트 완성
  .storybook/preview-head.html
  src/components/Search/Search.stories.tsx
  src/components/Search/Search.styled.tsx
  src/components/Search/Search.tsx
  src/components/Search/Search.type.ts
  src/components/SearchBar/SearchBar.stories.tsx
  src/components/SearchBar/SearchBar.styled.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/SearchBar.type.ts
  src/components/SearchBar/assets/icon-search.svg
  src/components/SuggestList/SuggestList.stories.tsx
  src/components/SuggestList/SuggestList.styled.tsx
  src/components/SuggestList/SuggestList.tsx
  src/components/SuggestList/SuggestList.type.ts
  src/components/index.ts
  src/index.html
  src/redux/api/normalizers.ts
  src/redux/api/types/fetchData.ts
  src/redux/api/v3.ts
  src/redux/storeTypes.ts
Labels: ✨Feature

#65 이미지 카드 컴포넌트 마크업 & 디자인 완료, auto play 토글 기능 구현
  package-lock.json
  src/components/ImageCard/ImageCard.stories.tsx
  src/components/ImageCard/ImageCard.styled.tsx
  src/components/ImageCard/ImageCard.tsx
  src/components/ImageCard/ImageCard.type.ts
  src/components/Video/Video.tsx
  src/components/Video/Video.type.ts
  src/components/index.ts
  src/redux/slices/listInfoReducer.ts
  yarn.lock
Labels: ✨Feature, 🎨 Html&css, 🥰 Accessibility

#81 Search 컴포넌트 수정
  src/components/Search/Search.styled.tsx
  src/components/Search/Search.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SuggestList/SuggestList.styled.tsx
Labels: 🐞Bug, ✨Feature

#75 스프린트 1주차 PR(Button, Avatar, ImageDetailPageHeader, Image)
  package-lock.json
  package.json
  src/assets/Button/arrow.svg
  src/assets/Button/present-box.svg
  src/components/Avatar/Avatar.stories.tsx
  src/components/Avatar/Avatar.styled.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/Avatar.type.ts
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.styled.tsx
  src/components/Button/Button.tsx
  src/components/Button/Button.type.tsx
  src/components/Image/Image.stories.tsx
  src/components/Image/Image.styled.tsx
  src/components/Image/Image.tsx
  src/components/Image/Image.type.ts
  src/components/PostHeader/PostHeader.stories.tsx
  src/components/PostHeader/PostHeader.styled.tsx
  src/components/PostHeader/PostHeader.tsx
  src/components/PostHeader/PostHeader.type.tsx
  src/components/index.ts
  src/theme/theme.d.ts
  src/theme/themes.ts
  src/util/formatUtils.ts
  src/util/typeUtils.ts
  yarn.lock
Labels: ✨Feature, 🔨 Refactor

#96 MainContainer 수정 및 SearchBar 수정
  src/components/MainContainer/BasicHeader/BasicHeader.styled.tsx
  src/components/MainContainer/BasicHeader/BasicHeader.tsx
  src/components/MainContainer/MainContainer.styled.tsx
  src/components/MainContainer/MainContainer.tsx
  src/components/MainContainer/MainContainer.type.ts
  src/components/Search/Search.tsx
  src/components/SearchBar/SearchBar.styled.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SuggestList/SuggestList.styled.tsx
  src/components/SuggestList/SuggestList.tsx
  src/components/SuggestList/SuggestList.type.ts
  src/hooks/useThrottle.tsx
  src/styles/GlobalStyle.tsx
Labels: 🐞Bug, ✨Feature, 🥰 Accessibility

#97 Masonry 레이아웃(=waterfall) 기본 구현(column수 고정만), 야무 강사님 피드백 일부 반영
  src/assets/Icon/animationPlayIcon.svg
  src/components/ImageCard/ImageCard.stories.tsx
  src/components/ImageCard/ImageCard.styled.tsx
  src/components/ImageCard/ImageCard.tsx
  src/components/ImageCard/ImageCard.type.ts
  src/components/MasonryGallery/MasonryGallery.styled.tsx
  src/components/MasonryGallery/MasonryGallery.tsx
  src/components/MasonryGallery/MasonryGallery.type.ts
  src/components/index.ts
  src/pages/Home/Home.tsx
  src/redux/storeTypes.ts
  src/styles/GlobalStyle.tsx
Labels: ✨Feature, 🥰 Accessibility

#100 fix: module 순서 변경
  src/components/index.ts
Labels: 🐞Bug

#106 translate3d 속성은 SC의 attrs를 이용해 클래스 무한 생성 방지
  src/components/ImageCard/ImageCard.tsx
  src/components/ImageCard/ImageCard.type.ts
  src/components/MasonryGallery/MasonryGallery.styled.tsx
  src/styles/GlobalStyle.tsx
Labels: 🔨 Refactor
