Repository team-badminton/imgar-frontend, pull requests merged in 2021-10, with the labels that each got.

#108 PostContents 컴포넌트 구현
  package-lock.json
  src/assets/Icon/arrow.svg
  src/assets/Icon/present-box.svg
  src/components/Avatar/Avatar.tsx
  src/components/Button/Button.stories.tsx
  src/components/PostContents/PostContents.stories.tsx
  src/components/PostContents/PostContents.styled.tsx
  src/components/PostContents/PostContents.tsx
  src/components/PostContents/PostContents.type.ts
  src/components/PostContents/assets/WaveUnderLine.svg
  src/components/PostHeader/PostHeader.tsx
  src/components/index.ts
  src/util/formatUtils.ts
Labels: ✨Feature

#112 API 요청 시 max-width 설정, ImageCard 마우스 오버 시 효과 수정, MasonryGalleryHeader 분리 및 리덕스로 관리
  src/components/DropDownList/DropDownList.styled.tsx
  src/components/DropDownList/DropDownList.tsx
  src/components/DropDownList/DropDownList.type.ts
  src/components/ImageCard/ImageCard.styled.tsx
  src/components/ImageCard/ImageCard.tsx
  src/components/MasonryGallery/MasonryGallery.tsx
  src/components/MasonryGallery/MasonryGalleryHeader.tsx
  src/components/index.ts
  src/pages/Home/Home.tsx
  src/redux/slices/listInfoReducer.ts
  src/redux/storeTypes.ts
Labels: 🐞Bug, ✨Feature

#119 이미지 카드 컨테이너 반응형 구현
  src/components/MasonryGallery/MasonryGallery.styled.tsx
  src/components/MasonryGallery/MasonryGallery.tsx
  src/components/MasonryGallery/MasonryGalleryHeader.tsx
  src/redux/slices/displayReducer.ts
  src/redux/storeTypes.ts
Labels: ✨Feature

#124 모달 구현 / Post 이미지 클릭시 줌 기능 구현
  src/components/Button/Button.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.styled.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/Modal.type.ts
  src/components/MoreButton/MoreButton.stories.tsx
  src/components/MoreButton/MoreButton.styled.tsx
  src/components/MoreButton/MoreButton.tsx
  src/components/MoreButton/MoreButton.type.tsx
  src/components/MoreButton/assets/icon/more.svg
  src/components/Picture/Picture.stories.tsx
  src/components/Picture/Picture.tsx
  src/components/Picture/Picture.type.ts
  src/components/PostContents/PostContents.stories.tsx
  src/components/PostContents/PostContents.styled.tsx
  src/components/PostContents/PostContents.tsx
  src/components/PostContents/PostContents.type.ts
  src/components/PostFigure/PostFigure.stories.tsx
  src/components/PostFigure/PostFigure.styled.tsx
  src/components/PostFigure/PostFigure.tsx
  src/components/PostFigure/PostFigure.type.ts
  src/components/PostFigure/assets/WaveUnderLine.svg
  src/components/index.ts
  src/styles/GlobalStyle.tsx
  src/theme/theme.d.ts
  src/theme/themes.ts
  src/util/styleUtils.ts
Labels: ✨Feature, 🎨 Html&css, 🔨 Refactor

#123 MainContainer 개편
  src/components/MainContainer/MainContainer.tsx
Labels: 🐞Bug

#127 fix: Search 컴포넌트 API import 주소 변경
  src/components/Search/Search.tsx
Labels: 🐞Bug

#122 uniform 레이아웃 구현, 이미지 컴포넌트 반응형 구현 추가
  src/assets/Icon/uniformLayoutIcon.svg
  src/components/ImageCard/ImageCard.stories.tsx
  src/components/ImageCard/ImageCard.styled.tsx
  src/components/ImageCard/ImageCard.tsx
  src/components/ImageCard/ImageCard.type.ts
  src/components/MasonryGallery/MasonryGallery.styled.tsx
  src/components/MasonryGallery/MasonryGallery.tsx
  src/components/MasonryGallery/MasonryGalleryHeader.tsx
  src/redux/slices/listInfoReducer.ts
Labels: ✨Feature, 🔨 Refactor

#129 접근성 준수를 위해 primayColor 색 변경, SVG에 title 속성 추가
  .storybook/main.js
  src/components/ImageCard/ImageCard.tsx
  src/custom.d.ts
  src/theme/themes.ts
  webpack/webpack.config.common.js
Labels: ⚙ Config, 🥰 Accessibility

#131 postFigure 컴포넌트에서type이 video/mp4인 경우 video 컴포넌트가 렌더링되도록 로직 추가
  src/components/PostContents/PostContents.tsx
  src/components/PostFigure/PostFigure.stories.tsx
  src/components/PostFigure/PostFigure.styled.tsx
  src/components/PostFigure/PostFigure.tsx
  src/components/PostFigure/PostFigure.type.ts
  src/components/Video/Video.tsx
  src/components/Video/Video.type.ts
  src/components/index.ts
Labels: ✨Feature

#133 Loading컴포넌트 추가, 코드 스플릿팅, 폰트 추가
  src/App/App.tsx
  src/components/Loading/Loading.stories.tsx
  src/components/Loading/Loading.styled.tsx
  src/components/Loading/Loading.tsx
  src/components/Loading/Loading.type.ts
  src/styles/GlobalStyle.tsx
  src/styles/fonts/ProximaNova-Bold.eot
  src/styles/fonts/ProximaNova-Bold.ttf
  src/styles/fonts/ProximaNova-Bold.woff
  src/styles/fonts/ProximaNova-Extrabld.eot
  src/styles/fonts/ProximaNova-Extrabld.ttf
  src/styles/fonts/ProximaNova-Extrabld.woff
  src/styles/fonts/ProximaNova-Regular.eot
  src/styles/fonts/ProximaNova-Regular.ttf
  src/styles/fonts/ProximaNova-Regular.woff
  src/util/styleUtils.ts
  webpack/webpack.config.common.js
Labels: ✨Feature, ⚙ Config

#144 Profile 페이지와 About탭
  src/components/Loading/Loading.styled.tsx
  src/components/MainContainer/BasicHeader/BasicHeader.tsx
  src/components/MainContainer/MainContainer.styled.tsx
  src/components/MainContainer/MainContainer.tsx
  src/components/MainContainer/MainContainer.type.ts
  src/components/Search/Search.tsx
  src/components/SearchBar/SearchBar.styled.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SuggestList/SuggestList.tsx
  src/components/SuggestList/SuggestList.type.ts
  src/components/TabNavigation/TabNavigation.stories.tsx
  src/components/TabNavigation/TabNavigation.styled.tsx
  src/components/TabNavigation/TabNavigation.tsx
  src/components/TabNavigation/TabNavigation.type.ts
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/Tooltip/Tooltip.styled.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/Tooltip.type.ts
  src/components/UserInfo/UserInfo.stories.tsx
  src/components/UserInfo/UserInfo.styled.tsx
  src/components/UserInfo/UserInfo.tsx
  src/components/UserInfo/UserInfo.type.ts
  src/index.html
  src/pages/Profile/Profile.styled.tsx
  src/pages/Profile/Profile.tsx
  src/pages/Profile/Profile.type.ts
  src/pages/Profile/ProfileAbout.tsx
  src/pages/Profile/ProfileCover.tsx
  src/redux/api/normalizers.ts
  src/redux/storeTypes.ts
  src/styles/GlobalStyle.tsx
  src/theme/theme.d.ts
  src/theme/themes.ts
  src/util/formatUtils.ts
  src/util/styleUtils.ts
Labels: ✨Feature

#138 waterfall 레이아웃 버그 해결, DropDownList 컴포넌트 리팩토링, API 호출
  .storybook/preview.js
  src/App/App.tsx
  src/components/DropDownList/DropDownList.stories.tsx
  src/components/DropDownList/DropDownList.styled.tsx
  src/components/DropDownList/DropDownList.tsx
  src/components/DropDownList/DropDownList.type.ts
  src/components/ImageCard/ImageCard.styled.tsx
  src/components/MasonryGallery/MasonryGallery.stories.tsx
  src/components/MasonryGallery/MasonryGallery.tsx
  src/components/MasonryGallery/MasonryGalleryHeader.tsx
  src/hooks/useResize.tsx
  src/pages/Home/Home.tsx
  src/redux/slices/listInfoReducer.ts
  src/redux/storeTypes.ts
Labels: 🐞Bug, ✨Feature, 🔨 Refactor

#145 코드 리뷰를 위한 pullRequest(gallery page의 post 댓글)
  src/assets/Icon/upIcon.svg
  src/components/Avatar/Avatar.tsx
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.styled.tsx
  src/components/Button/Button.tsx
  src/components/Button/Button.type.tsx
  src/components/PostComments/PostComment/PostComment.stories.tsx
  src/components/PostComments/PostComment/PostComment.styled.tsx
  src/components/PostComments/PostComment/PostComment.tsx
  src/components/PostComments/PostComments.stories.tsx
  src/components/PostComments/PostComments.tsx
  src/components/PostComments/PostComments.type.ts
  src/components/Vote/Vote.stories.tsx
  src/components/Vote/Vote.styled.tsx
  src/components/Vote/Vote.tsx
  src/components/Vote/Vote.type.tsx
  src/components/index.ts
  src/theme/theme.d.ts
  src/theme/themes.ts
Labels: ✨Feature

#147 SuggestList innerHTML 제거, Loading 접근성 추가, MainContainer에서 width 수정 가능, galleryWidth 리덕스에서 관리
  src/App/App.tsx
  src/components/Loading/Loading.tsx
  src/components/MainContainer/MainContainer.styled.tsx
  src/components/MainContainer/MainContainer.tsx
  src/components/MainContainer/MainContainer.type.ts
  src/components/MasonryGallery/MasonryGallery.tsx
  src/components/SuggestList/SuggestList.tsx
  src/index.html
  src/pages/Home/Home.tsx
  src/redux/slices/displayReducer.ts
  src/redux/storeTypes.ts
  src/styles/GlobalStyle.tsx
Labels: ✨Feature

#153 MasonryGallery 컴포넌트 수정, lazyLoading props 추가
  src/components/ImageCard/ImageCard.tsx
  src/components/ImageCard/ImageCard.type.ts
  src/components/MainContainer/MainContainer.styled.tsx
  src/components/MasonryGallery/MasonryGallery.styled.tsx
  src/components/MasonryGallery/MasonryGallery.tsx
  src/components/MasonryGallery/MasonryGallery.type.ts
  src/components/MasonryGalleryHeader/MasonryGalleryHeader.tsx
  src/components/Picture/Picture.tsx
  src/components/Picture/Picture.type.ts
  src/components/PostFigure/PostFigure.tsx
  src/components/Video/Video.tsx
  src/components/Video/Video.type.ts
  src/components/index.ts
  src/pages/Home/Home.styled.tsx
  src/pages/Home/Home.tsx
Labels: ✨Feature

#157 ImageCard 스토리북 수정, isAlbum 정보를 Gallery 페이지로 추가 전달
  src/components/ImageCard/ImageCard.stories.tsx
  src/components/ImageCard/ImageCard.tsx
  src/components/MasonryGalleryFields/MasonryGalleryFields.tsx
  src/components/MasonryGalleryHeader/MasonryGalleryHeader.tsx
  src/pages/Home/Home.tsx
Labels: ✨Feature

#161 feat: MasonryGallery 내부에서 컨테이너 크기가 변경될 때 마다 열을 계산해서 보여주는 방식으로 변경
  src/components/MasonryGallery/MasonryGallery.tsx
Labels: ✨Feature

#164 오류 수정
  src/components/MainContainer/MainContainer.styled.tsx
  src/components/MainContainer/MainContainer.tsx
  src/pages/Home/Home.tsx
Labels: 🐞Bug

#178 Button 컴포넌트 수정, Vote 컴포넌트 기능 추가, Picture 컴포넌트 수정, Modal 수정, assets(svg) 추가
  src/assets/Icon/gifIcon.svg
  src/assets/Icon/heartIcon.svg
  src/assets/Icon/imageIcon.svg
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/Button/Button.type.tsx
  src/components/Modal/Modal.tsx
  src/components/Picture/Picture.stories.tsx
  src/components/Picture/Picture.tsx
  src/components/Picture/Picture.type.ts
  src/components/PostFigure/PostFigure.tsx
  src/components/Vote/Vote.tsx
Labels: 🐞Bug, ✨Feature, 🥰 Accessibility

#185 동작할 수 있도록 추가 커밋 머지
  src/components/InputBox/InputBox.stories.tsx
  src/components/InputBox/InputBox.styled.tsx
  src/components/InputBox/InputBox.tsx
  src/components/InputBox/InputBox.type.ts
  src/components/SelectBoxList/SelectBoxList.styled.tsx
  src/pages/Profile/About/ProfileAbout.stories.tsx
  src/pages/Profile/Favorite/ProfileFavorite.stories.tsx
  src/pages/SearchResult/SearchResult.stories.tsx
  src/pages/SearchResult/SearchResult.styled.tsx
  src/pages/SearchResult/SearchResult.tsx
  src/pages/SearchResult/SearchResult.type.ts
  src/pages/SearchResult/SearchResultCover.tsx
  src/pages/SearchResult/SearchResultHeader.tsx
Labels: ✨Feature

#186 fix: containerWidth가 없는 경우 100%로 처리
  src/components/MainContainer/MainContainer.styled.tsx
  src/components/MainContainer/MainContainer.tsx
  src/components/SortList/SortList.tsx
  src/pages/Profile/Comments/ProfileCommentsItem.tsx
Labels: 🐞Bug

#193 버그수정 및 기능추가 (useUpdateLatestQuery 정의 외)
  src/components/Logo/Logo.styled.tsx
  src/components/MainContainer/BasicHeader/BasicHeader.styled.tsx
  src/components/MainContainer/BasicHeader/BasicHeader.tsx
  src/components/SearchBar/SearchBar.styled.tsx
  src/hooks/useUpdateLatestQuery.tsx
  src/index.tsx
  src/pages/Profile/About/ProfileAbout.tsx
  src/pages/Profile/Comments/ProfileComments.styled.tsx
  src/pages/Profile/Comments/ProfileComments.tsx
  src/pages/Profile/Comments/ProfileCommentsItem.tsx
  src/pages/Profile/Favorite/ProfileFavorite.tsx
  src/pages/Profile/Posts/ProfilePosts.tsx
  src/pages/SearchResult/SearchResult.tsx
  src/redux/slices/listInfoReducer.ts
  src/redux/storeTypes.ts
  src/util/jsxUtils.tsx
  src/util/styleUtils.ts
Labels: 🐞Bug, ✨Feature

#203 추가 개선
  src/components/MainContainer/MainContainer.tsx
  src/components/MasonryGalleryHeader/MasonryGalleryHeader.tsx
  src/components/PostSideRelativeList/PostSideRelativeList.tsx
  src/components/TagDetailHeader/TagDetailHeader.tsx
  src/hooks/useUpdateLatestQuery.tsx
  src/pages/Home/Home.tsx
  src/pages/Profile/Favorite/ProfileFavorite.tsx
  src/pages/Profile/Posts/ProfilePosts.tsx
  src/pages/SearchResult/SearchResult.styled.tsx
  src/pages/SearchResult/SearchResult.tsx
  src/pages/SearchResult/SearchResultHeader.tsx
  src/pages/TagDetail/TagDetail.tsx
  src/redux/slices/listInfoReducer.ts
  src/redux/storeTypes.ts
Labels: 🐞Bug, ✨Feature

#205 sortList 컴포넌트에 외부 클릭시 사라지는 기능 추가
  src/components/MasonryGalleryFields/MasonryGalleryFields.tsx
  src/components/SelectBox/SelectBox.tsx
  src/components/SelectBoxList/SelectBoxList.tsx
  src/components/SelectBoxList/SelectBoxList.type.ts
  src/components/SortList/SortList.tsx
Labels: ✨Feature
